name: jetleaf_lang
description: This library exposes extended Dart primitives, collections, optional types, I/O streams, date/time utilities, math types, regex, and more.
version: 1.0.0

publish_to: none

homepage: https://jetleaf.dev
repository: https://github.com/hapnium/jetleaf

topics:
- IO
- Collections
- Primitives
- Optional Types
- Math
- Date/Time
- Regex
- Backend

keywords:
- IO
- Collections
- Primitives
- Optional Types
- Math
- Date/Time
- Regex
- Backend

environment:
  sdk: 3.8.1

dependencies:
  meta: ^1.17.0

dev_dependencies:
  test: ^1.21.0
  lints: ^3.0.0